services:
  - type: web
    name: shrifal-handicrafts-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        fromDatabase:
          name: shrifal-handicrafts-db
          property: connectionString
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PHONEPE_MERCHANT_ID
        sync: false
      - key: PHONEPE_SALT_KEY
        sync: false
      - key: PHONEPE_SALT_INDEX
        value: 1
      - key: CLOUDINARY_CLOUD_NAME
        value: Shrifal-Handicraft
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://shrifalhandicrafts.netlify.app
